name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
    - name: Install Dependance (pnpm) 安装依赖
      run: | 
        npm install -g pnpm
        pnpm install
    - name: Build Production Code 生成生产环境代码
      run: |
        rm -rf dist 
        pnpm build
    - name: copy file via ssh password 上传代码到云主机
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY}}
        source: "dist/*"
        target: ${{secrets.TARGET}}
        overwrite: true
        